a=List["Land", "Land", "Enhancement", "Instant", "Artifact", "1/1 token", "1/1 token", "1/1 token", "1/1 token", "2/2 token", "2/2 token", "2/2 token", "3/3 token", "3/3 token", "4/4 token"]
b=RandomChoice[a]
Print["My first card is: ", b]
c = DeleteCases[a, b]
d = RandomChoice[c]
Print["My second card is: ", d]
e = DeleteCases[c, d]
f = RandomChoice[e]
Print["My third card is: ", f]
