Print["Your card is:"]
your = RandomSample[Range[13], 1]
Print[your]
Print["My card is:"]
mine = RandomSample[Range[13], 1]
Print[mine]
your ∖[GreaterEqual] mine
Print["You win!"] := If[your > mine]
Print["I win!"] := If[mine > your]
Print["A tie!"] := If[your == mine]
