Print["Your card is:"]
your = RandomInteger[{1, 52}]
Print[your]
Print["My card is:"]
mine = RandomInteger[{1, 52}]
Print[mine]
Which[your > mine, Print["You win!"], mine > your, Print["I win!"], your == mine, Print["It's a tie!"]]
