a=RandomInteger[{1, 100}, 2]
b=Sort[a]
Print["Your cards are ", b]
Print["Type y and hit enter when you are ready for me to play my lowest card"]
Input[]
c=RandomInteger[{1, 100}, 2]
d=TakeSmallest[c, 1]
Print["My card is ", d]
Print["Type y and hit enter when you are ready for me to play my second card"]
Input[]
e=TakeLargest[c, 1]
Print["My card is ", e]
