a=RandomInteger[{1, 100}, 2]
Print["Your cards are ", a]
Print["Type y and hit enter when you are ready for me to play my lowest card"]
Input[]
b=RandomInteger[{1, 100}]
Print["My card is ", b]
Print["Type y and hit enter when you are ready for me to play my second card"]
Input[]
c=RandomInteger[{1, 100}]
Print["My card is ", c]
