a=List[1,2, 3, 4, 5, 6, 7, 8, 9, 10]
b=RandomChoice[a]
Print["My first card is: ", b]
c = DeleteCases[a, b]
d = RandomChoice[c]
Print["My second card is: ", d]
e = DeleteCases[c, d]
f = RandomChoice[e]
Print["My third card is: ", f]
g = DeleteCases[e, f]
h = RandomChoice[g]
Print["My fourth card is: ", h]
j = DeleteCases[g, h]
k = RandomChoice[j]
Print["My fifth card is: ", k]
