exprod[] := (e = DeleteCases[a, b]; f = RandomChoice[e]; Print["My card is: ", f])
a=List[1,2, 3, 4, 5, 6, 7, 8, 9, 10]
b=RandomChoice[a]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
exprod[]
