a=WeatherData["Seattle", "Temperature", "NonMetricValue"]
Print[a]
b=Sunrise[]
Print["Sunrise :"]
Print[b]
c=Sunset[]
Print["Sunset :"]
Print[c]
d=WindSpeedData[]
Print["Wind speed :"]
Print[d]
e=WindDirectionData[]
Print["Wind direction :"]
Print[e]
f=SunPosition[]
Print["Sun position :"]
Print[f]
g=MoonPhase[]
Print["Moon phase :"]
Print[g]
h=DaylightQ[]
Print["Is it daylight? :"]
Print[h]
