b=RandomChoice[{1, 1, 1} -> {"I lose a card from my hand", "I gain a card to my hand", "My hand size stays the same"}]
Print[b]
a=RandomChoice[{6, 1} -> {"I don't play any tricks", "I play a trick"}]
Print[a]
z=RandomChoice[{3, 2, 1, 6} -> {"I give you one card you are looking for", "I give you two cards you are looking for", "I give you three cards you are looking for", "Go fish"}]
Print[z]
