a=List["Ace \[ClubSuit]", "2 \[ClubSuit]", "3 \[ClubSuit]", "4 \[ClubSuit]", "5 \[ClubSuit]", "6 \[ClubSuit]", "7 \[ClubSuit]", "8 \[ClubSuit]", "9 \[ClubSuit]", "10 \[ClubSuit]", "Jack \[ClubSuit]", "Queen \[ClubSuit]", "King \[ClubSuit]", "Ace \[SpadeSuit]", "2 \[SpadeSuit]", "3 \[SpadeSuit]", "4 \[SpadeSuit]", "5 \[SpadeSuit]", "6 \[SpadeSuit]", "7 \[SpadeSuit]", "8 \[SpadeSuit]", "9 \[SpadeSuit]", "10 \[SpadeSuit]", "Jack \[SpadeSuit]", "Queen \[SpadeSuit]", "King \[SpadeSuit]", "Ace \[DiamondSuit]", "2 \[DiamondSuit]", "3 \[DiamondSuit]", "4 \[DiamondSuit]", "5 \[DiamondSuit]", "6 \[DiamondSuit]", "7 \[DiamondSuit]", "8 \[DiamondSuit]", "9 \[DiamondSuit]", "10 \[DiamondSuit]", "Jack \[DiamondSuit]", "Queen \[DiamondSuit]", "King \[DiamondSuit]", "Ace \[HeartSuit]", "2 \[HeartSuit]", "3 \[HeartSuit]", "4 \[HeartSuit]", "5 \[HeartSuit]", "6 \[HeartSuit]", "7 \[HeartSuit]", "8 \[HeartSuit]", "9 \[HeartSuit]", "10 \[HeartSuit]", "Jack \[HeartSuit]", "Queen \[HeartSuit]", "King \[HeartSuit]"]
b=RandomChoice[a]
Print["My first card is: ", b]
c = DeleteCases[a, b]
d = RandomChoice[c]
Print["My second card is: ", d]
e = DeleteCases[c, d]
f = RandomChoice[e]
Print["My third card is: ", f]
g = DeleteCases[e, f]
h = RandomChoice[g]
Print["My fourth card is: ", h]
j = DeleteCases[g, h]
k = RandomChoice[j]
Print["My fifth card is: ", k]
l = DeleteCases[j, k]
(* another 5 for Michigan *)
bb=RandomChoice[l]
Print["My sixth card is: ", bb]
cb = DeleteCases[l, bb]
db = RandomChoice[cb]
Print["My seventh card is: ", db]
eb = DeleteCases[cb, db]
fb = RandomChoice[eb]
Print["My eight card is: ", fb]
gb = DeleteCases[eb, fb]
hb = RandomChoice[gb]
Print["My ninth card is: ", hb]
jb = DeleteCases[gb, hb]
kb = RandomChoice[jb]
Print["My tenth card is: ", kb]
(* another 2 for Michigan *)
bc=RandomChoice[a]
Print["My eleventh card is: ", bc]
cc = DeleteCases[a, bc]
dc = RandomChoice[cc]
Print["My twelfth card is: ", dc]
