a=RandomChoice[{"Black","White"}]
b=RandomChoice[{4,6} -> {"No creature","1/1 "a}, 1]
c=RandomChoice[{"Black","White"}]
d=RandomChoice[{5,5} -> {"No creature","2/2 "c}, 1]
e=RandomChoice[{"Black","White"}]
f=RandomChoice[{5,5} -> {"No creature","3/2 "e}, 1]
Print[b]
Print[d]
Print[f]
