a=RandomChoice[{"Black","White"}]
b=RandomChoice[{2,8} -> {"No creature","2/2 "a}, 1]
c=RandomChoice[{"Black","White"}]
d=RandomChoice[{3,7} -> {"No creature","3/3 "c}, 1]
e=RandomChoice[{"Black","White"}]
f=RandomChoice[{4,6} -> {"No creature","4/4 "e}, 1]
g=RandomChoice[{"Black","White"}]
h=RandomChoice[{5,5} -> {"No creature","5/4 "g}, 1]
Print[b]
Print[d]
Print[f]
Print[h]
