a=List["Fengarian", "Keeper", "Sun Dominion"]
d=List[1,2,3,4,5,6]
e=List["Cost", "Attack", "Defense"]
h=List["White", "Black"]
j=List["Fengarian", "Keeper", "Sun Dominion", "White", "Black"]
b=RandomChoice[j]
c=RandomChoice[a]
f=RandomChoice[d]
g=RandomChoice[e]
i=RandomChoice[h]
Print["Trump is: ", b]
Print["My card is: ", c, " ", i, " ", f, " ", g]
