myrand=RandomInteger[{1, 16}]
lettera=List["Guard(1)", "Guard(1)", "Guard(1)", "Guard(1)", "Guard(1)", "Priest(2)", "Priest(2)", "Baron(3)", "Baron(3)", "Handmaiden(4)", "Handmaiden(4)", "Prince(5)", "Prince(5)", "King(6)", "Countess(7)", "Princess(8)" ]
guardguess=List["Priest(2)", "Priest(2)", "Baron(3)", "Baron(3)", "Handmaiden(4)", "Handmaiden(4)", "Prince(5)", "Prince(5)", "King(6)", "Countess(7)", "Princess(8)" ]
Print["The card I play is:"]
mycard=Extract[myrand][lettera]
Print[mycard]
nextlist=Delete[lettera, myrand]
(*Print["Remaining cards:"]
Print[nextlist]*)
If[mycard == "Guard(1)", Print["I think your card is: ", RandomChoice[guardguess]]]
If[mycard == "Baron(3)", Print["High card wins! My other card is: ", RandomChoice[guardguess]]]
If[mycard == "Handmaiden(4)", Print["My hand has no effect from your cards this turn."]]
If[mycard == "Prince(5)", Print["Please discard your hand and draw a new hand."]]
If[mycard == "King(6)", Print["Please discard your card and take my card which is: ", RandomChoice[guardguess]]]
If[mycard == "Countess(7)", Print["Countess has to be discarded if my other card is Prince or King"]]
If[mycard == "Princess(8)", Print["I discarded the Princess, you win!"]]
