a=RandomChoice[{"H", "T"}]
Print["First coin toss is: ", a]
z=InputString["Please enter your guess for 3 coin toss sequence: "]
Print["Your guess is: ", z]
y=Characters[z]
Print["Character list is: ", y]
w=Part[z, 2]
Print["Second character is:, w]
