a=RandomChoice[{"H", "T"}]
Print["First coin toss is: ", a]
z=InputString["Please enter your guess for 3 coin toss sequence: "]
Print["Your guess is: ", z]
y=Characters[z]
w=Part[y, 1]
v=Part[y, 2]
u=Part[y, 3]
s=Which[v == "H", "T", v == "T", "H"]
Print["My guess is: ", s,w,v]
