a=RandomChoice[{"H", "T"}]
Print["First coin toss is: ", a]
z=InputString["Please enter your guess for 3 coin toss sequence: "]
Print["Your guess is: ", z]
y=Characters[z]
Print["Character list is: ", y]
w=Part[y, 1]
Print["First character is: ", w]
v=Part[y, 2]
Print["Second character is: ", v]
u=Part[y, 3]
Print["Third character is: ", u]
s=Which[v == "H", t == "T", v == "T", t =="H"]
Print["My first toss is: ", s]
